server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/KanbanDB
  application:
    name: eurekaKanbanService
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost